# Generated by Django 5.2 on 2025-04-27 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.IntegerField(choices=[(0, '标准间'), (1, '豪华间'), (2, '套房')], unique=True)),
                ('price', models.IntegerField()),
                ('facilities', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=7, unique=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('booking_status', models.IntegerField(choices=[(0, '已取消'), (1, '待入住'), (2, '已入住'), (3, '已完成')])),
                ('guest_name', models.CharField(max_length=50)),
                ('guest_phone', models.CharField(max_length=11)),
                ('guest_id_card', models.CharField(max_length=18)),
                ('guest_count', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('comment_time', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.roomdetail'),
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, '空闲'), (1, '已预订'), (2, '已入住')])),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
                ('room_password', models.CharField(blank=True, max_length=6, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'status'], name='booking_roo_date_546ac4_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'date'), name='unique_room_date')],
            },
        ),
    ]
