# Generated by Django 5.2 on 2025-04-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomdetail',
            name='facilities',
        ),
    ]
