# Generated by Django 5.2 on 2025-04-27 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_roomdetail_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomstatus',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_password',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='room_type',
            field=models.IntegerField(choices=[(1, '标准间'), (2, '豪华间'), (3, '套房')], unique=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room'], name='booking_boo_room_id_342ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in_date'], name='booking_boo_check_i_cba4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_out_date'], name='booking_boo_check_o_b6d243_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status'], name='booking_boo_booking_ce4985_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'booking_status'], name='booking_boo_room_id_cc3a33_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='booking_boo_check_i_89e08a_idx'),
        ),
        migrations.DeleteModel(
            name='RoomStatus',
        ),
    ]
